# Preamble
name: Deploy arfc.github.io to GitHub Pages

on:
  push:
  #  branches:
  #    - 'source'
  # enable workflow to be run manually
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

     # - uses: actions/cache@v2
     #   with:
     #     path: vendor/bundle
     #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
     #     restore-keys: |
     #           ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.0
          bundler-cache: true

      - name: Deploy the website
        run: bundle exec rake publish_via_cd
      
      - name: Push the changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
     #   uses: helaili/jekyll-action@v2
     #   with:
     #     token: ${{ secrets.GITHUB_TOKEN }}
     #     target_branch: 'master'
